### ISSUE TITLE
Sorting not reflected in selection checks

### ISSUE THREAD

**Issue by matthewturk** [bloomberg/ipydatagrid#213]
**Describe the bug**

When a sort is applied in the GUI, this is not reflected in the selection checks.

**To Reproduce**

 1. Create a random dataset
 2. Display an ipydatagrid of that dataset
 3. In the GUI, sort by a given column
 4. Select, and then observe the output of `selected_cell_values`, which reflect the original sorting

**Expected behavior**
I would expect that the returned values would be reflective of the in-GUI sorted values, *or* that they would not be available

**Screenshots**
![ipydatagrid_sorted](https://user-images.githubusercontent.com/89019/110318922-c4b5ae00-7fd3-11eb-8c1b-bbe97e5e2115.png)

**Environment (please complete the following information):**
- Ubuntu 20.04
- Python 3.9, ipydatagrid from conda-forge

**Comment by ibdafna** [comment]
Discussed this today. We will remove the selections when sorting is applied!

**Comment by ibdafna** [comment]
The bug is slightly different than the description given above. In fact, selections do clear for me when I sort. What does seem to be an issue is that `grid.selected_cell_values` operates on the local copy of the data model, which is **not** synced with the front-end copy when a sorting event is triggered on the front-end. So `selected_cell_values` in fact does return the correct values from the data model, but unfortunately that data model is out of sync.

**Comment by matthewturk** [comment]
@ibdafna My apologies for the confused report -- yes, what you're describing is exactly what I was trying to get across.

**Comment by ibdafna** [comment]
Fixed via #219

**Comment by ibdafna** [comment]
@matthewturk no worries at all, and thank you very much for taking the time to report! 😸
