### ISSUE TITLE
How to reference Multi-index in row dimension?

### ISSUE THREAD

**Issue by reckoner** [bloomberg/ipydatagrid#225]
**Is your feature request related to a problem? Please describe.**

I looked at the `ConditionalFormatting.ipynb` and I can see how to reference a Multi-index column, but how would you do the same for a Multi-index row?

**Describe the solution you'd like**
Some documentaation on how to reference a  Multi-index row.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ibdafna** [comment]
Could you elaborate on what the end goal is? I am asking, because the conditional formatting example formats a given cell based on the value of its sibling *on the same row*, so in that context, I am not sure how referencing the entire row would make sense. But it's more likely than not that I do not understand your end goal, so it would be helpful to know the details of your use case!

**Comment by reckoner** [comment]
If I have a data frame that has a multi-index on both columns and rows, then I don't understand how to reference the unique row, which for a multi-index, would have two (or more) components to uniquely describe it. Thus, with or without the multi-index of the row is uniquely specified by its components. From what I can tell `ipydatagrid` only supports column multi-index.

**Comment by ibdafna** [comment]
Apologies, I should have asked this in my previous post above - in what context are you looking to reference a cell? I still can't quite understand the use case. The only reason you see multi-dimensional indexing for columns in the `ConditionalFormatting` example is because we allow using nested column headers - with appropriate grouping and rendering. You should also be able to use multi-index rows, but these are not grouped, so each row is effectively a unique row number.  If you can provide me with a concrete example, using code, it would be very helpful.

**Comment by ibdafna** [comment]
Closing this for now, but let us know if you need further assistance. Thanks!
