### ISSUE TITLE
DataGrid doesn't display table, only text

### ISSUE THREAD

**Issue by user529481** [bloomberg/ipydatagrid#526]
**Describe the bug**
Calling `DataGrid()` in JupyterLab cell prints 
```
DataGrid(auto_fit_params={'area': 'all', 'padding': 30, 'numCols': None}, corner_renderer=None, default_render…
```
but doesn't display any table

**To Reproduce**
Run `pip install ipydatagrid` 
Create a pandas dataframe in cell and run cell
```py
from ipydatagrid import DataGrid

df = pd.DataFrame(...)
DataGrid(df)
```

**Expected behavior**
Should display table 

**Screenshots**
<img width="737" alt="Capture d’écran 2024-07-09 à 16 27 39" src="https://github.com/bloomberg/ipydatagrid/assets/71951740/cea19ec5-e94b-48c3-9485-ef974ca1b5f0">

**Environment (please complete the following information):**
 - Operating System and Version: MacOS 14.5
 - Browser [e.g. Firefox, Safari] (if applicable): JupyterLab Desktop

**Additional context**
Installed with `pip install ipydatagrid`

**Comment by xbrianh** [comment]
I see the same issue with ipydatagrid 1.3.2

**Comment by xbrianh** [comment]
This was resolved for me with:
```
pip install jupyter_contrib_nbextensions
```
and restarting my notebook server.

**Comment by martinRenou** [comment]
Note for the future reader that installing jupyter_nbcontrib_nbextensions will have no impact on installation issues for ipydatagrid. I would actually recommend not doing this as this is probably outdated now that jupyterlab is the official frontend for jupyter, and latest jupyter notebook depends on it.

**Restarting the Notebook server is important though**. Otherwise the ipydatagrid extension is not loaded by the server.
